// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkwtxyxxoomvxnnamaml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrd3R4eXh4b29tdnhubmFtYW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU5NTEsImV4cCI6MjA1Nzc4MTk1MX0.LAsxA3npzCghc2pwMTlAIY08IpGtmZtcIp4lD7Kc_sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);